apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: wordpress-app
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: clean-data
          image: alpine:3.18
          command: ["sh", "-c", "rm -rf /var/lib/mysql/* || true"]
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-storage
      containers:
        - name: mariadb
          image: mariadb:11.4
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: rootpass123
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-storage
      volumes:
        - name: mariadb-storage
          persistentVolumeClaim:
            claimName: mariadb-pvc
